# Generated by Django 4.1.3 on 2023-01-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koppee', '0010_rename_contdb_contactdb_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coffeedb',
            new_name='furnituredb',
        ),
    ]
